# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
defaults: &defaults
  docker:
    - image: circleci/ruby:2.7.0-node-browsers
      environment:
        RAILS_ENV: test
        PGHOST: 127.0.0.1
        POSTGRES_USER: root

    - image: circleci/postgres:9.5.15
      environment:
          POSTGRES_USER: root
          POSTGRES_DB: teamaj_rekordoj_test
  working_directory: ~/repo
    
version: 2
jobs:
  test:
    <<: *defaults

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      # run tests!
      - run:
          name: run tests
          command: bundle exec rspec
      - store_artifacts:
          path: coverage/
          destination: coverage
      - store_test_results:
          path: test/reports

  lint:
    <<: *defaults

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Run rubocop
      - run: bundle exec rubocop --fail-level=warning --display-cop-names --format=progress --format=offenses --format=html --out="rubocop.html"
      - store_artifacts:
          path: rubocop.html
          destination: rubocop.html
      - run: rm rubocop.html

  brakeman:
    <<: *defaults

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Update brakeman and run
      - run: bundle update brakeman --quiet
      - run: bundle exec brakeman -x CheckRender -o brakeman-output.html --no-progress --separate-models --exit-on-warn
      - store_artifacts:
          path: brakeman-output.html
          destination: brakeman-output.html

  deploy-staging:
    docker:
      - image: circleci/ruby:latest-browsers
    steps:
      - checkout
      - run: gem install dpl
      - run:
          name: Deploy Master to Heroku
          command: |
            dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_STAGING_API_KEY
          
workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      - lint
      - brakeman
      - deploy-staging:
          requires:
            - test
          filters:
            branches:
              only: master

